### PR TITLE
Insert title/numbered title menu actions

### PR DESCRIPTION
**Pull request by idle-code**
By making a pull request, you agree to the following terms:

```
"The contributor understands and agrees that Jendrik Seipp shall have
the irrevocable and perpetual right to make and distribute copies of
any contribution, as well as to create and distribute collective works
and derivative works of any contribution, under the GPL or under any
other open source license approved by the Open Source Initiative."
```

Summary of the changes in this pull request:
* Add `Insert>Title>Level 1-5` and `Insert>Numbered title>Level 1-5` menu actions for quick access to title formatting
* Minor refactor/cleanup of `InsertMenu` class

### CODE REVIEW

**Comment by idle-code** [comment]
If there are plans for Markdown then you are right about the numbered titles. I will remove them shortly, but should we do the same for normal titles? Markdown supports multiple levels of heading.

I prefer to divide my entries into subjects, each with its own headings. So as long as there is a quick way (keyboard shortcut) for adding a heading without the need for touching mouse - I will be happy.

**Comment by jendrikseipp** [comment]
Thanks for making the amendments. Very nice!

**Comment by jendrikseipp** [comment]
I just noticed two minor things: if no text is selected, pressing CTRL+1 should center the cursor between the two "equal (=)" signs. If text is selected and CTRL+1 is pressed, the same text should be selected as before. Do you agree?

**Comment by idle-code** [comment]
Yeah, that would be nice addition - I will look on it :)

**Pull request merged**
