### PR TITLE
Update help.py

### PR DESCRIPTION
**Pull request by ankurash**
Add instructions to change/apply themes in windows

By making a pull request, you agree to the following terms:

```
"The contributor understands and agrees that Jendrik Seipp shall have
the irrevocable and perpetual right to make and distribute copies of
any contribution, as well as to create and distribute collective works
and derivative works of any contribution, under the GPL or under any
other open source license approved by the Open Source Initiative."
```

Summary of the changes in this pull request:
* Update help.py: Add instructions to change/apply themes in windows

### CODE REVIEW

**Comment by jendrikseipp** [comment]
Thanks for the PR! I force-pushed a revision to master. Could you rebase your changes, please?

**Comment by ankurash** [comment]
I think I've rebased the changes on my master branch. I'm not entirely sure if I've done what you asked for. Please let me know if there's anything more on my part that I have to do.

**Comment by jendrikseipp** [comment]
Looks good. Thanks for your help! If you feel like submitting another pull request, please go ahead :-) I recommend discussing new features first, though, to make sure they're aligned with RedNotebook's goals.

**Comment by ankurash** [comment]
Hi, I'm not sure where and how to discuss new features. I have an idea, should I create a feature request for the discussion or is there some other way to discuss that?

**Comment by jendrikseipp** [comment]
Discussing this in a new issue sounds good.

**Pull request merged**
