### PR TITLE
Use latest debian compat method

### PR DESCRIPTION
**Pull request by kathenas**
Use latest debian compat method.

This removes need for 'debian/compat' file and puts all related control within 'debian/control'.

Current debhelper-compat is (= 13) for bullseye and sid, but we use (= 12) for buster (10.x stable distro) builds. We review later when at a time to submit for Debian distro inclusion.

Note: Merge after other PR.

### CODE REVIEW

**Comment by jendrikseipp** [comment]
It would be great if the launchpad PPA builds for Ubuntu Bionic (18.04) would still work after this change. The previous version bump from 10 to 11 removed support for Ubuntu 16.04, which is fine, but I'd like to keep support for 18.04 for now. Do you know if this change breaks the build for Ubuntu 18.04?

Could you tell me the commands you use to build the deb package, so I can add a test for GitHub Actions, please?

**Comment by kathenas** [comment]
On Sat, 2020-08-15 at 11:42 -0700, Jendrik Seipp wrote:
> It would be great if the launchpad PPA builds for Ubuntu Bionic
> (18.04) would still work after this change. The previous version bump
> from 10 to 11 removed support for Ubuntu 16.04, which is fine, but I'd
> like to keep support for 18.04 for now. Do you know if this change
> breaks the build for Ubuntu 18.04?
> Could you tell me the commands you use to build the deb package, so I
> can add a test for GitHub Actions, please?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

Hi,

If you merge PR up to date, I will setup an ubuntu build VM and make
sure of back to 18.04 compatibility. Any changes made I will comment to
make sure others know why a specific setting is in place.

I do all local builds using pbuilder. I would have to look at GitHub to
see what could be added for deb package builds. I will get back to you
on this one.

Regards

Phil

-- 

*** Playing the game for the games sake. ***

WWW: https://kathenas.org

Twitter: @kathenasorg

IRC: kathenas

GPG: 724AA9B52F024C8B

**Comment by kathenas** [comment]
debhelper-compat is at 11 in bionic proper (so updated PR). 12 is in bionic backports, but I do not think we need to burden users to have backports enabled.

**Comment by jendrikseipp** [comment]
Maybe we can use https://github.com/marketplace/actions/build-debian-package to test building the Debian package.

I think it's fine to use debhelper version 12 if that makes things easier on your end. We only need to support the launchpad servers (and they seem to have backports enabled). I don't envision any users on Ubuntu 18.04 trying to build the package themselves.

**Comment by kathenas** [comment]
Go with 11 for now and we can look at supporting Debian sid and backwards, Ubuntu latest and backwards and we can go from that point. I will dig deeper tomorrow into actions (the one you linked to) etc.

**Comment by jendrikseipp** [comment]
Sounds good!

**Pull request merged**
