### PR TITLE
Added sudo in front of the run command

### PR DESCRIPTION
**Pull request by belkinsa**
I added a sudo in front of the run command.  This for new users to Linux command line, they might not know that they need root to run a shell script.

### CODE REVIEW

**Comment by emvigo** [comment]
I know this is a very minor thing, but I think this is not the best way to express that you need to run that script as root. Instead of adding "sudo" to it (some distros do not bring sudo by default or it might be disabled by the sysadmin), I'd go for using the hash sign to show that you should be root, no matter how you get those privileges.

`# ./run`

Some further explanation additional to that will always be helpful, of course.

**Comment by jendrikseipp** [comment]
I think ideally the script shouldn't need any sudo privileges. Instead, if a package is missing, the appropriate command for installing it should be printed. What do we need to change, so that the run script doesn't need sudo privileges anymore?

**Comment by emvigo** [comment]
Ideally the script should not even exist. Dependency checking is something that should be done by the package manager... (I'm who packages Rednotebook for Arch in the AUR, BTW). Is this meant for those users that want to install Rednotebook directly from source?

**Comment by jendrikseipp** [comment]
Good point! The script is meant for users who want to run RedNotebook without installation. I have removed the dependency installation parts from the script. Now it only calls the main script with the correct Python interpreter. I'd still like to keep the script around in case we want to include building the translation locally, etc. Also, many online guides mention the run script.

Now that the script definitely doesn't need any super user privileges, I'm closing this PR.

**Comment by jendrikseipp** [comment]
Thanks for bringing this up though @belkinsa! This definitely needed some cleaning up...

**Comment by belkinsa** [comment]
Not a problem.  I could help on writing docs for the command including the reason behind the "." before the run command.

I'm running it without installation because I'm planning to make a [electronic lab note respin off of RNB](http://senseopenness.com/goals-for-y-cycle/).

**Comment by jendrikseipp** [comment]
Your respin sounds interesting, would love to hear where you take this idea.

I think the run script doesn't need more than the existing documentation. There are other parts of the code and docs that need more love :)

**Pull request closed without merging**
