### PR TITLE
Fixed the run script. The error occurred if executed the script in a …

### PR DESCRIPTION
**Pull request by smolin35**
…non rednotebook directory.

By making a pull request, you agree to the following terms:

```
"The contributor understands and agrees that Jendrik Seipp shall have
the irrevocable and perpetual right to make and distribute copies of
any contribution, as well as to create and distribute collective works
and derivative works of any contribution, under the GPL or under any
other open source license approved by the Open Source Initiative."
```

Summary of the changes in this pull request:
* TODO

### CODE REVIEW

**Comment by jendrikseipp** [comment]
I guess you're seeing this error because your RedNotebook dir is symlinked. Is that correct?

**Comment by smolin35** [comment]
Sorry, my English is so so.

I have simlink to the rednotebook/run in the /bin directory.
When I exec the run through the symbolic link, script return error: 
python3: can't open file 'rednotebook/journal.py': [Errno 20] Not a directory

**Comment by jendrikseipp** [comment]
You can simply symlink directly to rednotebook/journal.py. Feel free to reopen this, if that doesn't work.

**Comment by smolin35** [comment]
Symlink directly to rednotebook/journal.py not work. I get error: Access is denied. 
Also, I get the same error when I run it directly rednotebook/rednotebook/journal.py. At the same time, when you start rednotebook/run, the app starts

**Comment by jendrikseipp** [comment]
This should be fixed now.

**Comment by smolin35** [comment]
Thanks )

**Pull request closed without merging**
