### PR TITLE
Add dir=auto to p tags on markdown to html conversion

### PR DESCRIPTION
**Pull request by metemaddar**
## Summary of the changes in this pull request

* Improved bidirectional text support: Enhanced the preview mode to display bidirectional texts (e.g., mixed RTL and LTR languages) correctly for improved readability and compatibility with multilingual content.

## Pull request checklist

- [x] I have added an entry in `CHANGELOG.md` including my name and issue and/or pull request number.
- [x] If applicable: I have removed the corresponding entry in `TODO.md`.

Related issue: #781

### CODE REVIEW

**Comment by metemaddar** [comment]
Guys found a better idea. I put this PR on draft for now.

**Comment by jendrikseipp** [comment]
> Guys found a better idea. I put this PR on draft for now.

What's the idea?

**Comment by metemaddar** [comment]
> What's the idea?
I'm not fully sure about the idea. But I think they decided to change the underlying functions for converter. or pass options to it. But I think this PR also can be fine.

**Comment by jendrikseipp** [comment]
I propose to add dir=auto to the top html element instead. Can you export your journal to HTML, do this change manually and check if everything looks correct to you?

**Comment by metemaddar** [comment]
> I propose to add dir=auto to the top html element instead. Can you export your journal to HTML, do this change manually and check if everything looks correct to you?

Yes. I understand. But this doesn't do the job. The `dir="auto"` works only on the direct text under the tag. So we need to pass the `dir="auto"` to all the `<p>` tags.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir):

> **auto**, which lets the user agent decide. It uses a basic algorithm as it parses the characters inside the element until it finds a character with a strong directionality, then applies that directionality to the whole **element**.

**Comment by jendrikseipp** [comment]
But the same page says
> [Inheritance](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir#inheritance)
>If an element has no dir attribute, it will inherit the dir value set on its [parent node](https://developer.mozilla.org/en-US/docs/Glossary/Node/DOM), which in turn may inherit it from its parent, and so on.

I had ChatGPT create a test case for this:

```
<!DOCTYPE html>
<html dir="auto">
<head>
    <meta charset="UTF-8">
</head>
<body>
    مرحباً! هذا نص باللغة العربية. 12345.
    <p>
        This is a test sentence in English, which flows from left to right. 12345.
    </p>

    <p>
        Only English.
    </p>

    <p>
        مرحباً! هذا نص باللغة العربية. 12345.
    </p>

    <p>
        Text starts in English, ثم ينتقل إلى العربية, and ends in English.
    </p>

    <p>
        12345 - الأرقام وحدها لا تحدد الاتجاه. يجب إضافة كلمات لتحديد الاتجاه.
    </p>

    <p>
        שלום עולם! This sentence starts in Hebrew but includes English words.
    </p>

    <p>
        Hello world! وهناك بعض الكلمات باللغة العربية في النهاية.
    </p>
</body>
</html>
```

Loading this HTML page in Firefox, let's all the text flow from right to left. If I remove the first sentence (so that the document starts with English text) or if I remove dir="auto", all the text flows from left to right. Can you confirm this?

**Comment by metemaddar** [comment]
> Loading this HTML page in Firefox, let's all the text flow from right to left. If I remove the first sentence (so that the document starts with English text) or if I remove dir="auto", all the text flows from left to right. Can you confirm this?

Yes exactly. This changes the direction of the whole test to right, as it started with an rtl character. But I think in most cases its not what the user wants (This is how for example Linkedin manages the posts). But in text editors like VS-Code, this applys per line.

For example the test text becomes like this:
```

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
</head>
<body>
    مرحباً! هذا نص باللغة العربية. 12345.
    <p dir="auto">
        This is a test sentence in English, which flows from left to right. 12345.
    </p>

    <p dir="auto">
        Only English.
    </p>

    <p dir="auto">
        مرحباً! هذا نص باللغة العربية. 12345.
    </p>

    <p dir="auto">
        Text starts in English, ثم ينتقل إلى العربية, and ends in English.
    </p>

    <p dir="auto">
        12345 - الأرقام وحدها لا تحدد الاتجاه. يجب إضافة كلمات لتحديد الاتجاه.
    </p>

    <p dir="auto">
        שלום עולם! This sentence starts in Hebrew but includes English words.
    </p>

    <p dir="auto">
        Hello world! وهناك بعض الكلمات باللغة العربية في النهاية.
    </p>
</body>
</html>
```

For example imagine you are writing in an rtl language, And you need to show a programming in the middle of the text. You need to make it LTR. You can start the paragraph with an English character and it will do the job.

**Comment by metemaddar** [comment]
This is how the preview works in original red notebook:

Screenshot from 2024-12-18 00-47-50

And also by adding `dir="auto"` to all p tags (This PR) that desired:

Screenshot from 2024-12-18 00-47-34

**Comment by jendrikseipp** [comment]
Thanks, now I understand. I'll look into the PR.

**Comment by jendrikseipp** [comment]
Thanks for your help!

**Pull request merged**
